### ISSUE TITLE
[JOSS Review] Statement of need

### ISSUE THREAD

**Issue by melund** [finsberg/pulse#1]
Hi Henrik. I think the "statement of need" should be extended to clearly state what pulse provides which isn't already in FEniCS, and why it is needed. It may be obvious to someone within the field but not to an outsider. 

It applies to both the documentation, JOSS paper, and maybe the readme on Github.

**Comment by finsberg** [comment]
Hi Morten, 

I have now updated the [paper.md](https://github.com/openjournals/joss-papers/blob/joss.01539/joss.01539/10.21105.joss.01539.pdf) in the joss folder as well as the [README](https://github.com/finsberg/pulse/blob/master/README.md) and the [documentation page](https://finsberg.github.io/pulse/html/index.html) to be more specific of what is the difference between FEniCS and pulse. 

Let me know if you think this looks OK or not.

**Comment by melund** [comment]
Thanks, @finsberg. I think that covers it nicely.
