### ISSUE TITLE
[JOSS Review] In what OSI license family does the License belong?

### ISSUE THREAD

**Issue by melund** [finsberg/pulse#2]
JOSS seem to require a OSI appoved license for the work. I can't, however, see what OSI license family the [LICENSE](https://github.com/finsberg/pulse/blob/master/LICENSE) falls under. 

Maybe this is an issue with your obligations to Simula, but I think could be possible to find an OSI license which enforces the same conditions.

**Comment by finsberg** [comment]
Changed LICENSE to LGPL.
