### ISSUE TITLE
Benchmark problem1

### ISSUE THREAD

**Issue by jingbinzhao415** [finsberg/pulse#28]
Hi Dr. Finsberg,

When I ran the benchmark problem1, I have the below errors:

**2022-03-15 18:20:41,039 [3752] CRITICAL root: Traceback (most recent call last):
  File "beam_problem1.py", line 95, in <module>
    problem.solve()
  File "/home/jingbin/.local/lib/python3.8/site-packages/pulse/mechanicsproblem.py", line 360, in solve
    raise SolverDidNotConverge("Solver did not converge...")
pulse.mechanicsproblem.SolverDidNotConverge: Solver did not converge...**

Could you please help me check with that? I very be very grateful for your assistance!

Thank you,
Jingbin

**Comment by finsberg** [comment]
Hi Jingbin,

Could you give a little information about how you installed fenics?
The following steps works for me

```
git clone https://github.com/finsberg/pulse.git
cd pulse
docker run --rm -v $(pwd):/shared -w /shared -it finsberg/fenics-extra
python -m pip install -e .
cd demo/benchmark
python problem1.py
```

**Comment by finsberg** [comment]
You need to give me some more information. What is the version of pulse do you have
```
python -c "import pulse; print(pulse.__version__)"
```
What is the version of FEniCS
```
python -c "import dolfin; print(dolfin.__version__)"
```
What type of computer are you using. Are you running Ubuntu in wsl?
Does this problem occur with all the demos or only `problem1.py`

**Comment by jingbinzhao415** [comment]
![image](https://user-images.githubusercontent.com/93218388/158929804-3fd4c3f0-1a66-44b4-a2e4-201d9c5c133f.png)

I used the pulse version is : 2021.1.2 and the dolfin version is: 2019.2.0.dev0.
This problem only occurred with this benchmark_problem1.

Thank you,
Jingbin

**Comment by finsberg** [comment]
OK, try to upgrade to the latest version of pulse

**Comment by wilburmao** [comment]
Hi Finsberg,

I encountered the same problem as Jingbin, even after I updated the pulse to 2022.1.0.
I am running the ubuntu 20.04 in wsl. 
Here is my error information.

$ python3 problem1.py
*** Warning: PETSc SNES solver diverged in 0 iterations with divergence reason DIVERGED_LINEAR_SOLVE.
2022-03-27 00:42:02,533 [4044] CRITICAL root: Traceback (most recent call last):
  File "problem1.py", line 95, in <module>
    problem.solve()
  File "/home/wilburmao/.local/lib/python3.8/site-packages/pulse/mechanicsproblem.py", line 369, in solve
    raise SolverDidNotConverge("Solver did not converge...")
pulse.mechanicsproblem.SolverDidNotConverge: Solver did not converge...

Thank you for your help.
Wilbur

**Comment by finsberg** [comment]
OK, thanks for reporting this. I tried to swap the linear solver from `super_lu_dist` to `mumps` (https://github.com/finsberg/pulse/commit/b7835a7e79109e5830493321ab9c12c93982a5c6). If you try to upgrade to the latest version 
```
python3 -m pip install fenics-pulse --upgrade
```
you should get this automatically. Let me know how it goes.

**Comment by wilburmao** [comment]
Thank you for the update. Now, all benchmark problems work properly on my end.

**Comment by finsberg** [comment]
Great! I am closing this then.
