### ISSUE TITLE
How to fix the freedom of apex node in benchmark Problem3

### ISSUE THREAD

**Issue by wilburmao** [finsberg/pulse#35]
In benchmark Problem3 code, the base surface is fixed in all directions. I also try to fix the apex_epi node in the x & y directions (in-plane motion is fixed), although it may not be necessary for this example. Here is the code I added,

```python
# Define Dirichlet boundary. Fix the apex in the x & y directions
def apex_x(W):
    V = W if W.sub(0).num_sub_spaces() == 0 else W.sub(0)
    return DirichletBC(
        V.sub(0),
        Constant(0.0),
        geometry.vfun,
        geometry.markers["APEX_EPI"][0],
    )

def apex_y(W):
    V = W if W.sub(0).num_sub_spaces() == 0 else W.sub(0)
    return DirichletBC(
        V.sub(1),
        Constant(0.0),
        geometry.vfun,
        geometry.markers["APEX_EPI"][0],
    )

# Collect Boundary Conditions
bcs = pulse.BoundaryConditions(dirichlet=(dirichlet_bc,apex_x,apex_y,), neumann=(neumann_bc,))
# Create problem
problem = pulse.MechanicsProblem(geometry, material, bcs)
```

When I create the problem, it gives the error "pulse.mechanicsproblem: DirichletBC only implemented for as callable. Please provide DirichletBC as a callable with argument being the state space only". So I wonder what is wrong with my code. 

Thank you,
Wilbur

**Comment by finsberg** [comment]
You should only supply one callable to `pulse.BoundaryConditions`, so e.g

```python
# Define Dirichlet boundary. Fix the apex in the x & y directions
def dirichlet_bc(W):
    V = W if W.sub(0).num_sub_spaces() == 0 else W.sub(0)
    return [
    DirichletBC(
        V.sub(0),
        Constant(0.0),
        geometry.vfun,
        geometry.markers["APEX_EPI"][0],
    ), 
    DirichletBC(
        V.sub(1),
        Constant(0.0),
        geometry.vfun,
        geometry.markers["APEX_EPI"][0],
    )]

# Collect Boundary Conditions
bcs = pulse.BoundaryConditions(dirichlet=(dirichlet_bc,), neumann=(neumann_bc,))

**Comment by finsberg** [comment]
I do see now that the API is not very intuitive, and it shouldn't be too difficult to support "your approach".

**Comment by wilburmao** [comment]
Even with this updated function, I encountered the same error. I suspect the error is due to geometry.vfun.
I was able to define two dirichlet BCS with two facet functions.
def dirichlet_bc2(W):
    V = W if W.sub(0).num_sub_spaces() == 0 else W.sub(0)
    return [
        DirichletBC(
        V,
        Constant((0.0, 0.0, 0.0)),
        geometry.ffun,
        geometry.markers["BASE"][0],
    ),
    DirichletBC(
        V.sub(0),
        Constant(0.0),
        geometry.ffun,
        geometry.markers["ENDO"][0],
    )]
# Collect Boundary Conditions
bcs = pulse.BoundaryConditions(dirichlet=(dirichlet_bc2,), neumann=(neumann_bc,))
Could you check this error? Thanks.

**Comment by finsberg** [comment]
If you are using the vertex function (i.e `geometry.vfun`), did you set the method to `"pointwise"`? See e.g https://computationalmechanics.in/boundary-conditions-in-fenics/ for some examples of pointwise boundary conditions.

**Comment by wilburmao** [comment]
The "pointwise" method is added to the definition. Still received the same error. Any advice? 

# Define Dirichlet boundary. Fix the apex in the x & y directions
def dirichlet_bc(W):
    V = W if W.sub(0).num_sub_spaces() == 0 else W.sub(0)
    return [
    DirichletBC(
        V.sub(0),
        Constant(0.0),
        geometry.vfun,
        geometry.markers["APEX_EPI"][0],
        method = "pointwise",
    ), 
    DirichletBC(
        V.sub(1),
        Constant(0.0),
        geometry.vfun,
        geometry.markers["APEX_EPI"][0],
        method = "pointwise",
    ),
    DirichletBC(
        V,
        Constant((0.0, 0.0, 0.0)),
        geometry.ffun,
        geometry.markers["BASE"][0],
    )]

RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to create Dirichlet boundary condition.
*** Reason:  User MeshFunction is not a facet MeshFunction (dimension is wrong).
*** Where:   This error was encountered inside DirichletBC.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2019.1.0
*** Git changeset:  7f46aeb0b296da5bbb1fb0845822a72ab9b09c55
*** -----------------------------------------------------------

**Comment by finsberg** [comment]
Maybe this is relevant https://fenicsproject.discourse.group/t/setting-dirichlet-boundary-condition-constraint-on-3d-edges/5249/3

**Comment by wilburmao** [comment]
Thank you for your advice. I think I solved it finally. Here is the code:


```python
# Define Dirichlet boundary. Fix the apex (at x[0]=-20) in the y & z directions
def dirichlet_bc1(W):
    V = W if W.sub(0).num_sub_spaces() == 0 else W.sub(0)
    return [
    DirichletBC(
        V.sub(1),
        Constant(0.0),
        "near(x[0],-20)",
        method = "pointwise",
    ), 
    DirichletBC(
        V.sub(2),
        Constant(0.0),
        "near(x[0],-20)",
        method = "pointwise",
    ),
    DirichletBC(
        V,
        Constant((0.0, 0.0, 0.0)),
        geometry.ffun,
        geometry.markers["BASE"][0],
    )]
```
I think geometry.vfun should not be used to apply bc on vertices.
