### ISSUE TITLE
How to generate fiber and facet data in demo\from_xml

### ISSUE THREAD

**Issue by wilburmao** [finsberg/pulse#36]
Hi Finsberg,

I wonder how you generate the fiber.xml and facet_function.xml files in the demo. I know the mesh file can be generated by dolfin-convert. And the fiber orientations can be generated by another package 'ldrb' created by you. But the file written by ldrb is not in the same format as fiber.xml. This is important if the mesh is created by other software. Thanks.

**Comment by finsberg** [comment]
If you have the fibers in a dolfin function, say `fibers`, then you can save it to xml using the following syntax
```
import dolfin
dolfin.File("fiber.xml") << fiber
```
That's said, the `xml`-format is deprecated and you should probably use either HDF5 or XDMF instead, see e.g https://fenicsproject.discourse.group/t/transitioning-from-mesh-xml-to-mesh-xdmf-from-dolfin-convert-to-meshio/412

The same goes with the `MeshFunction`. The content of the file `facet_function.xml` is basically the same as the content of the file loaded here: https://github.com/finsberg/ldrb/blob/bf19aa5dcac692b1532386c8ca410e696235308c/demos/demo_lv.py#L49

And the facet function is created in these lines: https://github.com/finsberg/ldrb/blob/bf19aa5dcac692b1532386c8ca410e696235308c/ldrb/utils.py#L268-L278

**Comment by finsberg** [comment]
You might also get some inspiration from this repo: https://github.com/ComputationalPhysiology/cardiac_geometries

**Comment by wilburmao** [comment]
Thank you.
I ended up using pyvista package to wrap the volume and surface meshes and save it to the gmsh format file. Then this file can be read into the pulse with the ffun to do the FE analysis.
