### ISSUE TITLE
[JOSS Review] Consider automated tests

### ISSUE THREAD

**Issue by melund** [finsberg/pulse#5]
Seeing the nice tests suite written with pytest it is a shame that there are no automated regression tests. I would suggest that for any open source project. @finsberg is there any reason you have chosen manual tests only? 

Note. This is non-blocker for the JOSS review.  Current manual tests are acceptable.

**Comment by finsberg** [comment]
As a regression test I am running all the demos as a part of the continuous integration (see [.circleci/config.yml](https://github.com/finsberg/pulse/blob/master/.circleci/config.yml). @melund  do you suggest adding more regression tests?

**Comment by melund** [comment]
No. That is absolutely fine. Sorry I missed the CircleCI badge. My fault :)
