### ISSUE TITLE
[JOSS Review] Consider a Conda-forge package

### ISSUE THREAD

**Issue by melund** [finsberg/pulse#6]
This is also a non-blocker for the review.

I very much recommend that you considered a conda-forge package for Pulse. I think it would help keep the library alive and ensure that it would continue to work for future versions of FEniCS and other dependencies.

**Comment by finsberg** [comment]
I agree it would be great to put this on conda-forge. 

There seems to be some issues with the 2017 version for FEniCS on conda-forge, so perhaps it would make sense to wait until `pulse` is up to date with the most recent version of FEniCS (version 2019). I have created an [issue](https://github.com/finsberg/pulse/issues/4) for this and also started a [new branch](https://github.com/finsberg/pulse/tree/fenics2019).

**Comment by finsberg** [comment]
I have now opened a pull request in order to put pulse on conda-forge, see here: https://github.com/conda-forge/staged-recipes/pull/9012

**Comment by finsberg** [comment]
`pulse` is now available on conda-forge (https://github.com/conda-forge/pulse-feedstock)
