### ISSUE TITLE
Benchmark Problems 2 & 3

### ISSUE THREAD

**Issue by Tao-Bath** [finsberg/pulse#97]
Hi Finsberg,

The deformed apex locations at the endo- and epicardium for Benchmark Problems 2 & 3 differ quite a lot from the results of Simula-FEniCS in the Cardiac Mechanic Benchmark paper. Would you happen to know what caused that error? I cannot figure it out.. Thank you!!

**Comment by finsberg** [comment]
The results of the Simula-FEniCS contribution of the Cardiac Mechanics Benchmark paper are generated with the source code from here: https://bitbucket.org/peppu/mechbench/src/master/. One big difference between this code and the original code from the paper is that problem 2 and 3 uses the the 2D axisymmetric geometry in the code published in the paper. 

Looking at the paper now, I agree that the results from the docs differ quite a lot from the results in the paper. I don't have a good answer to this now, and I also don't really have the time to investigate this in detail, but I would encourage you to try out the 3D version of the original code https://bitbucket.org/peppu/mechbench/src/master and maybe compare that source code with pulse. Would also be great if you could report back, if you find any mistakes.

**Comment by finsberg** [comment]
Since the geometry is a truncated ellipsoid the fibers can be computed analytically (similar to what is done here: https://github.com/ComputationalPhysiology/cardiac_geometries/blob/main/src/cardiac_geometries/fibers/_lv_ellipsoid.py). In other words, you don't need to use `ldrb` for the fibers (and this is also not the fibers used in the problem description). Also I think CG-1 is not a good function space to use for the fibers. You will see in the original code that they used a Quadrature space for this ( https://bitbucket.org/peppu/mechbench/src/cf17394f0b85f5110909a71440ce2d78f3d4c7fa/ellipsoidgeometry.py#lines-128).

For your specific error, you should try to uninstall dolfin-adjoint / pyadjoint (or set the environment variable `DOLFIN_ADJOINT=0`)

**Comment by Tao-Bath** [comment]
Hi Finsberg,

I've tried using cardiac_geometries to generate fibre direction and insert it into the code Problem3.py (https://github.com/finsberg/pulse/blob/e51c3fb974c3028765e289669a191d9855dffaa4/demo/benchmark/problem3.py#L20):

`import cardiac_geometries`
`geometry = pulse.HeartGeometry.from_file(pulse.mesh_paths["benchmark"])`
`microstructure = cardiac_geometries.fibers._lv_ellipsoid.create_microstructure(
            mesh=geometry.mesh,
            ffun=geometry.marker_functions.ffun,
            markers=geometry.markers,
            function_space="Quadrature_4",
            r_short_endo=7,
            r_short_epi=10,
            r_long_endo=17,
            r_long_epi=20,
            alpha_endo=90,
            alpha_epi=-90,
        )`
`geometry.microstructure=microstructure`

Then I got the divide-by-zero error when when normalising vectors (https://github.com/ComputationalPhysiology/cardiac_geometries/blob/1f786b4ad02d2bcfe5465d9aca1fd70252c5044f/src/cardiac_geometries/fibers/_lv_ellipsoid.py#L55)

I replaced the function "normalize" by:
`def normalize(u):
    norm_u = np.linalg.norm(u, axis=0)
    zero_norm_indices = np.where(norm_u == 0)
    u_normalized = np.divide(u, norm_u, out=np.zeros_like(u), where=norm_u!=0)
    u_normalized[:, zero_norm_indices[0]] = 0  # Set all elements to zero where norm is zero
    return u_normalized`

it seems to fix the error and in the end, I got the results of the apex location:

`Get longitudinal position of endocardial apex: 11.9393 mm`
`Get longitudinal position of epicardial apex: 15.2203 mm`
 which seems to be closer to Figure 9 in the paper

But I am still confused why the results of Problem2 also differ since it only has passive stress. Would you happen to have any suggestions?

Thank you very much!

**Comment by finsberg** [comment]
I agree this is strange. I will dig deeper a try to see why this is happening. I have started to port the old simula code from the mechanics benchmark from https://bitbucket.org/peppu/mechbench/src/master/ to https://github.com/finsberg/mechbench/tree/fenics2019 and in this case I do get the correct numbers. Feel free to see if you can spot the error. I will also spend some time on trying to figure this out.

**Comment by Tao-Bath** [comment]
Hi Finsberg,

I just want to report to you that the parameter name should be "C" instead of "CC" in problem2 `https://github.com/finsberg/pulse/blob/6ff3fd54f59dede4b69b40e57531838d7a021232/demo/benchmark/problem2.py#L31`

This typo was also found in problem3, but it doesn't matter since the default_parameter in Guccione.py is correct "C":2.0

Thank you for your help and updating the software!

**Comment by finsberg** [comment]
Yes, I also found that error and fixed it in https://github.com/finsberg/pulse/pull/98. Also updated the code to use `cardiac-geometries` to generate the meshes, and problem 3 seems to also work as expected now. Thanks for reporting this issue.

**Comment by Tao-Bath** [comment]
Hi Finsberg,

I am trying to run the updated benchmark problem3.py after updating cardiac-geometries. But I got the error for generating geometry by running:
`if not geo_path.is_dir():
    cg.create_benchmark_geometry_land15(outdir=geo_path)`

I got the error message:
WARNING  cardiac_geometries.fibers._utils: Unable to write XDMF file:
*** Error:   Unable to find element family.
*** Reason:  Element Quadrature not yet supported.

It seems to fail to write XDMF for quadrature elements. But the fiber is stored in microstructure.h5 only I think.

Then the following code doesn't work since geo.f0, geo.s0, geo.n0 not exist.

`geo = cg.geometry.Geometry.from_folder(geo_path)`
`geometry = pulse.HeartGeometry(
    mesh=geo.mesh,
    markers=geo.markers,
    marker_functions=pulse.MarkerFunctions(vfun=geo.vfun, ffun=geo.ffun),
    microstructure=pulse.Microstructure(f0=geo.f0, s0=geo.s0, n0=geo.n0),
)`

Do you know how to fix it? Thank you!!
